# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

permissions:
     contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore BaseLibrary/
    - name: Build
      run: dotnet build BaseLibrary/ --no-restore -c Release
    - name: Test
      run: dotnet test BaseLibrary/ --no-build -c Release --verbosity normal
    - name: Pack
      run: dotnet pack BaseLibrary/BaseLibrary/BaseLibrary.csproj -c Release
    - name: Add  source
      run: dotnet nuget add source github
    - name: Publish
      run: dotnet nuget push "BaseLibrary/BaseLibrary/bin/Release/BaseLibrary.1.0.0.nupkg"  --api-key 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 --source "github"
